version: "3.4"
name: django-app

services:
  postgresql:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  postgresql-test:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: db-test
    ports:
      - "5431:5432"
    volumes:
      - ./test_pgdata:/var/lib/postgresql/data

  
  backend:
    env_file:
      - ./.env
    build:
      dockerfile: ./backend/Dockerfile

    volumes:
      - ./backend:/backend
    command: /bin/sh -c 'python backend/manage.py runserver 0.0.0.0:5001'
    ports:
      - "5001:5001"
    depends_on:
      - postgresql
    stdin_open: true
    tty: True
