# Generated by Django 5.0.3 on 2024-04-12 12:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(),
        ),
    ]
